fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "vmware": "git://github.com/ghoneycutt/puppet-module-vmware.git"
  symlinks:
    "virtual": "#{source_dir}"
