fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
    'vmware': 'git://github.com/ghoneycutt/puppet-module-vmware.git'
  symlinks:
    'virtual': "#{source_dir}"
